import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

// import bootstrap CSS
import "bootstrap/dist/css/bootstrap.min.css";
// import bootstrap JS
import Bootstrap from '@/app/components/bootstrap';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Bootstrap />
      </body>
    </html>
  );
}
